- job:
    name: build-compute-hyperv-sphinx-docs
    parent: build-openstack-sphinx-docs
    description: |
      Run tox sphinx docs job with the nova dependency.
    vars:
      tox_install_siblings: true
    required-projects:
      - openstack/nova

- project:
    templates:
      - openstack-lower-constraints-jobs
      - release-notes-jobs-python3
    check:
      jobs:
        - build-compute-hyperv-sphinx-docs
    gate:
      jobs:
        - build-openstack-releasenotes
        - build-compute-hyperv-sphinx-docs
